[build]
  command = "gimme 1.19.13 && pip install -r requirements.txt && python3 -m flask build && python3 -m flask compress"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "14"
  PIP_VERSION = "21.3.1"
