[build]
  image = "node:14"
  command = "curl -sL -o gimme https://raw.githubusercontent.com/travis-ci/gimme/master/gimme && chmod +x gimme && ./gimme 1.19.x && conda env create -f environment.yml && conda activate ishiring-env && python3 -m flask build && python3 -m flask compress"

[[plugins]]
  package = "netlify-plugin-hashid"
  [plugins.inputs]
    folder = "dist/"
    extensions = ["html", "css", "js", "json", "svg", "png", "jpg", "jpeg", "webp", "gif"]

[[plugins]]
  package = "netlify-plugin-image-optim"
  [plugins.inputs]
    folder = "dist/"
    ignore = "**/*.+(svg|gif)"
    lossy = true
    quality = 75
    webp = true
    avif = false
    concurrent = 10

[build.environment]
  NODE_VERSION = "14"
  PATH = "/opt/buildhome/.gimme/versions/go1.19.linux.amd64/bin:$PATH"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'none'; manifest-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
