[build]
  command = "gimme 1.16 && conda create --name ishiring.fyi --file environment.yml && conda activate ishiring.fyi && python3 -m flask build && python3 -m flask compress"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "14"
  CONDA_VERSION = "4.10.3"
