[build]
  image = "python:3.9"
  command = "pip install -r requirements.txt && python -m flask build && python -m flask compress"

[[plugins]]
  package = "netlify-plugin-hashid"
  [plugins.inputs]
    folder = "dist/"
    extensions = ["html", "css", "js", "json", "svg", "png", "jpg", "jpeg", "webp", "gif"]

[[plugins]]
  package = "netlify-plugin-image-optim"
  [plugins.inputs]
    folder = "dist/"
    ignore = "**/*.+(svg|gif)"
    lossy = true
    quality = 75
    webp = true
    avif = false
    concurrent = 10

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'none'; manifest-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
