name: Schedule script

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update actions/github-script to latest version
      run: |
        sed -i 's/actions\/github-script@.*$/actions\/github-script@v4/g' main.yml

    - name: Run script
      uses: actions/github-script@v4
      with:
        script: |
          chmod +x script.sh && ./emails.py

