name: Schedule script

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: chmod +x script.sh && ./emails.py

